"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Section="today"|"patrols"|"projects"|"stottly"|"week"|"watch"|"month"|"long";
type Task={id:string;title:string;section:Section;day?:string;due?:string;recurring?:boolean;done:boolean;created:string;completed?:string};
type Meal={logged:boolean;note:string};
type OuraDay={sleepScore?:number;readinessScore?:number;activityScore?:number;stressMinutes?:number;recoveryMinutes?:number;resilience?:string};
type Health={date:string;sleep:string;energy:number;mood:number;hydration:number;bloodSugar:string;exercise:string;notes:string;emotion:string;emotionIntensity:number;anxiety:number;stress:number;regulated:number;trigger:string;response:string;helped:string;medsTaken:string[];meals:{breakfast:Meal;lunch:Meal;dinner:Meal};oura?:OuraDay};
type Morning={date:string;sleepQuality:string;energy:number;emotion:string;focus:string;needs:string[]};
type State={tasks:Task[];health:Health[];revenue:{date:string;amount:number;source:string}[];mornings:Morning[];medNames:string[]};
type View="home"|"week"|"health"|"kpi"|"data";

const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const labels:Record<Section,string>={today:"Today",patrols:"Daily maintenance & patrols",projects:"Personal projects",stottly:"Stottly Enterprises",week:"This week",watch:"Keep an eye on",month:"This month",long:"Long term"};
const now=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
const blankMeal=():Meal=>({logged:false,note:""});
const blankHealth=(date=today()):Health=>({date,sleep:"",energy:5,mood:5,hydration:0,bloodSugar:"",exercise:"",notes:"",emotion:"",emotionIntensity:5,anxiety:5,stress:5,regulated:5,trigger:"",response:"",helped:"",medsTaken:[],meals:{breakfast:blankMeal(),lunch:blankMeal(),dinner:blankMeal()}});
const seed:Task[]=[
 ...["Best Buy","Laundry","Dishes","4 PM Floor Walk","1 hour Coursera"].map((title,i)=>({id:`t${i}`,title,section:"today" as Section,due:title.startsWith("4 PM")?"16:00":"",done:false,created:now()})),
 ...["Job Patrol","Continue Application Vigilance","Theater Jobs","Auditions","Gig Patrol","Acting Class","Re-examine entrepreneur options","Targeted resume drops","Targeted ways to make money","Targeted cash business","Targeted travel opportunities"].map((title,i)=>({id:`p${i}`,title,section:"patrols" as Section,recurring:true,done:false,created:now()})),
 {id:"pj1",title:"Personal build out PNP — include daily health tracker",section:"projects",done:false,created:now()},
 ...["10 Jobs","Work punch list on Forge","Re-evaluate subscription model Forge","Work PnP"].map((title,i)=>({id:`s${i}`,title,section:"stottly" as Section,day:"Monday",done:false,created:now()})),
 ...[["Interview Massage Envy","Tuesday"],["MMJ followup","Wednesday"],["Spider-Man with Hen","Thursday"],["Date with Kim","Friday"]].map(([title,day],i)=>({id:`w${i}`,title,section:"week" as Section,day,done:false,created:now()})),
 ...["Disability","Food Stamps","Medicare"].map((title,i)=>({id:`e${i}`,title,section:"watch" as Section,done:false,created:now()})),
 ...["Clear AC line","Paint bedroom","Downstairs bathroom","Paint door","Returns","Pool — Black Algae Hunt","Bug spray","Tree and bush trim"].map((title,i)=>({id:`m${i}`,title,section:"month" as Section,done:false,created:now()})),
 ...["Keep working house","Keep up on applications","Unconventional but legal income opportunities"].map((title,i)=>({id:`l${i}`,title,section:"long" as Section,done:false,created:now()}))
];
const initial:State={tasks:seed,health:[],revenue:[],mornings:[],medNames:["Morning medications","Vitamins / supplements","TRT (Monday / Thursday)"]};
const storageKey="pnp-v1";

function normalize(raw:Partial<State>):State{
 return{
  tasks:raw.tasks||seed,revenue:raw.revenue||[],mornings:raw.mornings||[],medNames:raw.medNames||initial.medNames,
  health:(raw.health||[]).map(h=>({...blankHealth(h.date),...h,medsTaken:h.medsTaken||((h as Health&{meds?:boolean}).meds?["Morning medications"]:[]),meals:h.meals||blankHealth(h.date).meals}))
 };
}

export default function Home(){
 const [data,setData]=useState<State>(initial),[ready,setReady]=useState(false),[view,setView]=useState<View>("home");
 const [health,setHealth]=useState<Health>(blankHealth()),[adding,setAdding]=useState<Section|null>(null),[title,setTitle]=useState("");
 const [morningOpen,setMorningOpen]=useState(false),[morningStep,setMorningStep]=useState(0);
 const [morning,setMorning]=useState<Morning>({date:today(),sleepQuality:"",energy:5,emotion:"",focus:"",needs:[]});
 const [income,setIncome]=useState({amount:"",source:""}),[newMed,setNewMed]=useState("");
 const [oura,setOura]=useState({configured:false,connected:false,syncing:false,message:""});
 const backupRef=useRef<HTMLInputElement>(null),healthRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setData(normalize(JSON.parse(saved)))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify(data))},[data,ready]);
 useEffect(()=>{const saved=data.health.find(x=>x.date===today());if(saved)setHealth(normalize({...initial,health:[saved]}).health[0])},[data.health]);
 useEffect(()=>{fetch("/api/oura/status").then(r=>r.json()).then(x=>setOura(o=>({...o,...x}))).catch(()=>{})},[]);

 const toggle=(id:string)=>setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,done:!t.done,completed:!t.done?now():undefined}:t)}));
 const remove=(id:string)=>setData(d=>({...d,tasks:d.tasks.filter(t=>t.id!==id)}));
 const edit=(id:string)=>{const old=data.tasks.find(t=>t.id===id),v=prompt("Edit task",old?.title);if(v?.trim())setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,title:v.trim()}:t)}))};
 const add=()=>{if(!adding||!title.trim())return;setData(d=>({...d,tasks:[...d.tasks,{id:crypto.randomUUID(),title:title.trim(),section:adding,done:false,created:now()}]}));setAdding(null);setTitle("")};
 const move=(id:string,dir:number)=>setData(d=>{const a=[...d.tasks],i=a.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return d;[a[i],a[j]]=[a[j],a[i]];return{...d,tasks:a}});
 const saveHealth=()=>setData(d=>({...d,health:[...d.health.filter(x=>x.date!==health.date),health].sort((a,b)=>a.date.localeCompare(b.date))}));
 const finishMorning=()=>{setData(d=>({...d,mornings:[...d.mornings.filter(x=>x.date!==morning.date),morning]}));setHealth(h=>({...h,energy:morning.energy,emotion:morning.emotion||h.emotion}));setMorningOpen(false);setMorningStep(0)};
 const toggleNeed=(n:string)=>setMorning(m=>({...m,needs:m.needs.includes(n)?m.needs.filter(x=>x!==n):[...m.needs,n]}));
 const toggleMed=(n:string)=>setHealth(h=>({...h,medsTaken:h.medsTaken.includes(n)?h.medsTaken.filter(x=>x!==n):[...h.medsTaken,n]}));
 const meal=(name:keyof Health["meals"],patch:Partial<Meal>)=>setHealth(h=>({...h,meals:{...h.meals,[name]:{...h.meals[name],...patch}}}));
 const currentMorning=data.mornings.find(x=>x.date===today());
 const greeting=()=>{const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening"};
 const stats=useMemo(()=>{const done=data.tasks.filter(t=>t.done).length,total=data.tasks.length,recent=data.health.slice(-7);const avg=(k:"energy"|"mood"|"anxiety"|"stress"|"regulated")=>recent.length?(recent.reduce((s,x)=>s+(Number(x[k])||0),0)/recent.length).toFixed(1):"—";const meals=recent.reduce((s,x)=>s+Object.values(x.meals||{}).filter(m=>m.logged).length,0);return{done,total,rate:total?Math.round(done/total*100):0,energy:avg("energy"),mood:avg("mood"),anxiety:avg("anxiety"),stress:avg("stress"),regulated:avg("regulated"),sleep:recent.length?(recent.reduce((s,x)=>s+(+x.sleep||0),0)/recent.length).toFixed(1):"—",meals,revenue:data.revenue.reduce((s,x)=>s+x.amount,0)}},[data]);
 const report=`PROGRESS, NOT PERFECTION — WEEKLY KPI REPORT\n${new Date().toLocaleDateString()}\n\nTasks completed: ${stats.done} of ${stats.total} (${stats.rate}%)\nMorning interviews: ${data.mornings.slice(-7).length}\nMeals logged: ${stats.meals} of 21\nAverage sleep: ${stats.sleep} hours\nAverage energy: ${stats.energy}/10\nAverage mood: ${stats.mood}/10\nAverage anxiety: ${stats.anxiety}/10\nAverage stress: ${stats.stress}/10\nAverage emotional regulation: ${stats.regulated}/10\nIncome recorded: $${stats.revenue.toLocaleString()}\n\nProgress is evidence, not a verdict. Emotions are information, not grades.`;
 const exportJson=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`progress-not-perfection-${today()}.json`;a.click()};
 const importJson=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{setData(normalize(JSON.parse(String(r.result))))}catch{alert("That file could not be imported.")}};r.readAsText(f)};
 const importHealthCsv=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const [head,...rows]=String(r.result).trim().split(/\r?\n/).map(x=>x.split(","));const entries=rows.map(row=>Object.fromEntries(head.map((h,i)=>[h.trim(),row[i]?.trim()||""]))).filter(x=>x.date).map(x=>({...blankHealth(x.date),sleep:x.sleep||"",energy:+x.energy||5,mood:+x.mood||5,hydration:+x.hydration||0,bloodSugar:x.bloodSugar||"",exercise:x.exercise||""}));setData(d=>({...d,health:[...d.health.filter(x=>!entries.some(e=>e.date===x.date)),...entries].sort((a,b)=>a.date.localeCompare(b.date))}));alert(`Imported ${entries.length} health entries.`)}catch{alert("Use CSV columns: date,sleep,energy,mood,hydration,bloodSugar,exercise")}};r.readAsText(f)};
 const syncOura=async()=>{setOura(o=>({...o,syncing:true,message:"Syncing your ring…"}));try{const res=await fetch("/api/oura/sync");const body=await res.json();if(!res.ok)throw new Error(body.error||"Sync failed");setData(d=>({...d,health:[...d.health.filter(x=>!body.days.some((v:{date:string})=>v.date===x.date)),...body.days.map((v:{date:string;oura:OuraDay;sleepHours?:number})=>({...blankHealth(v.date),sleep:v.sleepHours?String(v.sleepHours):"",oura:v.oura}))].sort((a,b)=>a.date.localeCompare(b.date))}));setOura(o=>({...o,syncing:false,message:`Synced ${body.days.length} days from Oura.`}))}catch(e){setOura(o=>({...o,syncing:false,message:e instanceof Error?e.message:"Sync failed"}))}};

 const TaskList=({section,day}:{section:Section;day?:string})=>{const list=data.tasks.filter(t=>t.section===section&&(!day||t.day===day));return <div className="tasklist">{list.map(t=><div className={`task ${t.done?"done":""}`} key={t.id}><button className="check" onClick={()=>toggle(t.id)} aria-label={`Mark ${t.title} ${t.done?"not done":"done"}`}>{t.done?"✓":""}</button><button className="taskname" onClick={()=>edit(t.id)}>{t.title}{t.due&&<small>{t.due}</small>}</button><div className="tasktools"><button onClick={()=>move(t.id,-1)} aria-label="Move up">↑</button><button onClick={()=>move(t.id,1)} aria-label="Move down">↓</button><button onClick={()=>remove(t.id)} aria-label="Delete">×</button></div></div>)}{!day&&<button className="add" onClick={()=>setAdding(section)}>＋ Add item</button>}</div>};
 if(!ready)return null;

 return <main>
  <aside><div className="brand"><span>PNP</span><div>Progress,<br/>Not Perfection</div></div><nav>{[["home","Today"],["week","Week"],["health","Health"],["kpi","KPIs & reports"],["data","Data & backup"]].map(([id,label])=><button className={view===id?"active":""} onClick={()=>setView(id as View)} key={id}>{label}</button>)}</nav><p>Your life, observed kindly.<br/><b>Forge-free by design.</b></p></aside>
  <section className="content">
   <header><div><p className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</p><h1>{view==="home"?`${greeting()}, Dan.`:view==="week"?"Your week, at a glance.":view==="health"?"Care for the whole system.":view==="kpi"?"Pull the signal.":"Your data is yours."}</h1></div><div className="principle">Progression over perfection</div></header>
   {view==="home"&&<><section className="welcome"><div><p>{currentMorning?`You checked in this morning. Your focus: ${currentMorning.focus||"use the day with intention"}.`:"Take two quiet minutes. Notice where you are, then choose the day."}</p><h2>{currentMorning?"You showed up for yourself today.":"How are you arriving today?"}</h2></div><button className="warm" onClick={()=>setMorningOpen(true)}>{currentMorning?"Review morning interview":"Start morning interview"} →</button></section><div className="metrics"><article><label>Forward motion</label><strong>{stats.rate}%</strong><span>{stats.done} items complete</span></article><article><label>Energy · 7-day</label><strong>{stats.energy}</strong><span>out of 10</span></article><article><label>Meals · 7-day</label><strong>{stats.meals}/21</strong><span>breakfast · lunch · dinner</span></article></div><div className="grid"><Card title={labels.today}><TaskList section="today"/></Card><Card title={labels.patrols} wide><TaskList section="patrols"/></Card><Card title={labels.projects}><TaskList section="projects"/></Card><Card title={labels.stottly}><TaskList section="stottly"/></Card><Card title={labels.watch}><TaskList section="watch"/></Card><Card title={labels.month}><TaskList section="month"/></Card><Card title={labels.long} wide><TaskList section="long"/></Card></div></>}
   {view==="week"&&<div className="week">{days.map(d=><Card title={d} key={d}><TaskList section="week" day={d}/><div className="weekStottly"><TaskList section="stottly" day={d}/></div></Card>)}</div>}
   {view==="health"&&<div className="healthGrid"><Card title="Medications" wide><p className="hint">First things first. Tap each item as you take it.</p><div className="tapgrid">{data.medNames.map(n=><button key={n} className={`tap ${health.medsTaken.includes(n)?"selected":""}`} onClick={()=>toggleMed(n)}><span>{health.medsTaken.includes(n)?"✓":"○"}</span>{n}</button>)}</div><div className="inline"><input value={newMed} onChange={e=>setNewMed(e.target.value)} placeholder="Add medication or supplement"/><button onClick={()=>{if(newMed.trim()){setData(d=>({...d,medNames:[...d.medNames,newMed.trim()]}));setNewMed("")}}}>Add</button></div></Card>
    <Card title="Meals · three anchors" wide><p className="hint">Logging food is context, not judgment.</p><div className="meals">{(["breakfast","lunch","dinner"] as const).map(name=><div className={`meal ${health.meals[name].logged?"logged":""}`} key={name}><button onClick={()=>meal(name,{logged:!health.meals[name].logged})}><span>{health.meals[name].logged?"✓":"＋"}</span>{name}</button><input value={health.meals[name].note} onChange={e=>meal(name,{note:e.target.value})} placeholder={`What was ${name}?`}/></div>)}</div></Card>
    <Card title="Daily health & emotional check-in" wide><div className="form"><div className="subhead full"><b>Body & capacity</b><span>Tap first. Type only when useful.</span></div><label>Date<input type="date" value={health.date} onChange={e=>setHealth(blankHealth(e.target.value))}/></label><label>Sleep (hours)<input inputMode="decimal" type="number" step=".25" value={health.sleep} onChange={e=>setHealth({...health,sleep:e.target.value})}/></label><Scale label="Energy" value={health.energy} onChange={energy=>setHealth({...health,energy})}/><Scale label="Mood" value={health.mood} onChange={mood=>setHealth({...health,mood})}/><label>Hydration<div className="counter"><button onClick={()=>setHealth({...health,hydration:Math.max(0,health.hydration-1)})}>−</button><b>{health.hydration} glasses</b><button onClick={()=>setHealth({...health,hydration:health.hydration+1})}>＋</button></div></label><label>Blood sugar<input inputMode="decimal" value={health.bloodSugar} onChange={e=>setHealth({...health,bloodSugar:e.target.value})} placeholder="Optional"/></label><div className="subhead full"><b>Movement</b></div><Choice label="What moved today?" options={["Walk","Pool","Strength","Mobility","Rest day"]} value={health.exercise} onChange={exercise=>setHealth({...health,exercise})}/><div className="subhead full"><b>Emotional check-in</b><span>Emotions are information, not grades.</span></div><Choice label="Primary emotion" options={["Calm","Joy","Hopeful","Anxious","Low","Angry","Irritable","Overwhelmed"]} value={health.emotion} onChange={emotion=>setHealth({...health,emotion})}/><Scale label="Intensity" value={health.emotionIntensity} onChange={emotionIntensity=>setHealth({...health,emotionIntensity})}/><Scale label="Anxiety" value={health.anxiety} onChange={anxiety=>setHealth({...health,anxiety})}/><Scale label="Stress" value={health.stress} onChange={stress=>setHealth({...health,stress})}/><Scale label="Regulation" value={health.regulated} onChange={regulated=>setHealth({...health,regulated})}/><label>Trigger or context<input value={health.trigger} onChange={e=>setHealth({...health,trigger:e.target.value})} placeholder="Only if useful"/></label><label>How I responded<input value={health.response} onChange={e=>setHealth({...health,response:e.target.value})} placeholder="What did I do next?"/></label><Choice label="What helped?" options={["Food","Water","Rest","Movement","Pool","Music","Conversation","Quiet"]} value={health.helped} onChange={helped=>setHealth({...health,helped})}/><label className="full">Anything else?<textarea value={health.notes} onChange={e=>setHealth({...health,notes:e.target.value})} placeholder="Optional notes"/></label><button className="primary save" onClick={saveHealth}>Save today’s check-in</button></div></Card>
    <Card title="Oura connection"><p className="body">Bring in sleep, readiness, activity, daily stress, and resilience from your Oura Ring. Oura stays in control of permission and you can disconnect at any time.</p><div className="ouraStatus"><span className={oura.connected?"dot on":"dot"}/><b>{oura.connected?"Oura connected":oura.configured?"Ready to connect":"Oura setup required"}</b></div><div className="connects">{oura.connected?<><button className="primary" disabled={oura.syncing} onClick={syncOura}>{oura.syncing?"Syncing…":"Sync Oura now"}</button><a className="buttonLink" href="/api/oura/disconnect">Disconnect</a></>:oura.configured?<a className="buttonLink primary" href="/api/oura/connect">Connect Oura</a>:<button disabled>Add Oura credentials in Vercel</button>}<button onClick={()=>healthRef.current?.click()}>Import health CSV</button><input hidden ref={healthRef} type="file" accept=".csv,text/csv" onChange={e=>importHealthCsv(e.target.files?.[0])}/></div>{oura.message&&<p className="successNote">{oura.message}</p>}<p className="micro">Oura requires OURA_CLIENT_ID, OURA_CLIENT_SECRET, and APP_URL in Vercel.</p></Card>
    <Card title="Recent entries">{data.health.slice(-7).reverse().map(h=><div className="healthrow" key={h.date}><b>{h.date}</b><span>{h.sleep||"—"}h sleep</span>{h.oura?.readinessScore&&<span>Readiness {h.oura.readinessScore}</span>}{h.oura?.sleepScore&&<span>Oura sleep {h.oura.sleepScore}</span>}<span>Energy {h.energy}</span><span>{Object.values(h.meals||{}).filter(m=>m.logged).length}/3 meals</span>{h.emotion&&<span>{h.emotion}</span>}</div>)}</Card></div>}
   {view==="kpi"&&<><div className="metrics kpis"><Metric label="Completion" value={`${stats.rate}%`} note={`${stats.done}/${stats.total} items`}/><Metric label="Morning interviews" value={String(data.mornings.slice(-7).length)} note="last seven"/><Metric label="Meals logged" value={`${stats.meals}/21`} note="last seven check-ins"/><Metric label="Avg sleep" value={stats.sleep} note="hours"/><Metric label="Avg energy" value={stats.energy} note="out of 10"/><Metric label="Avg mood" value={stats.mood} note="out of 10"/><Metric label="Avg anxiety" value={stats.anxiety} note="out of 10"/><Metric label="Avg stress" value={stats.stress} note="out of 10"/><Metric label="Avg regulation" value={stats.regulated} note="out of 10"/></div><div className="split"><Card title="Weekly summary"><pre>{report}</pre><button className="primary" onClick={()=>navigator.clipboard.writeText(report)}>Copy report</button></Card><Card title="Record income"><div className="form one"><label>Amount<input type="number" value={income.amount} onChange={e=>setIncome({...income,amount:e.target.value})}/></label><label>Source<input value={income.source} onChange={e=>setIncome({...income,source:e.target.value})} placeholder="Client, gig, job…"/></label><button className="primary" onClick={()=>{if(+income.amount)setData(d=>({...d,revenue:[...d.revenue,{date:today(),amount:+income.amount,source:income.source||"Unspecified"}]}));setIncome({amount:"",source:""})}}>Add income</button></div></Card></div></>}
   {view==="data"&&<div className="split"><Card title="Backup & portability"><p className="body">Everything stays in this browser. Export regularly and import on another device when needed.</p><div className="actions"><button className="primary" onClick={exportJson}>Export JSON</button><button onClick={()=>backupRef.current?.click()}>Import JSON</button><input hidden ref={backupRef} type="file" accept=".json" onChange={e=>importJson(e.target.files?.[0])}/></div></Card><Card title="Private by default"><p className="body">Your entries are stored on this device, not in GitHub or a remote database. Clearing browser data removes them unless you have exported a backup.</p></Card></div>}
  </section>
  {adding&&<Modal close={()=>setAdding(null)}><h2>Add to {labels[adding]}</h2><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="What needs attention?"/><div className="actions"><button onClick={()=>setAdding(null)}>Cancel</button><button className="primary" onClick={add}>Add item</button></div></Modal>}
  {morningOpen&&<Modal close={()=>setMorningOpen(false)}><div className="interview"><p className="eyebrow">Morning interview · {morningStep+1} of 5</p>{morningStep===0&&<><h2>How did you sleep?</h2><Choice options={["Rough","Restless","Okay","Good","Restored"]} value={morning.sleepQuality} onChange={sleepQuality=>setMorning({...morning,sleepQuality})}/></>}{morningStep===1&&<><h2>How much energy is here?</h2><Scale value={morning.energy} onChange={energy=>setMorning({...morning,energy})}/></>}{morningStep===2&&<><h2>What feeling is closest?</h2><Choice options={["Calm","Hopeful","Good","Anxious","Low","Irritable","Overwhelmed"]} value={morning.emotion} onChange={emotion=>setMorning({...morning,emotion})}/></>}{morningStep===3&&<><h2>What would make today meaningful?</h2><input autoFocus value={morning.focus} onChange={e=>setMorning({...morning,focus:e.target.value})} placeholder="One clear focus—not a whole list"/></>}{morningStep===4&&<><h2>What do you need today?</h2><div className="chips">{["Food","Water","Medication","Movement","Rest","Quiet","Connection","Fun"].map(n=><button className={morning.needs.includes(n)?"selected":""} onClick={()=>toggleNeed(n)} key={n}>{n}</button>)}</div><p className="affirm">You do not have to earn care. You only have to notice what would help.</p></>}<div className="interviewNav">{morningStep>0&&<button onClick={()=>setMorningStep(s=>s-1)}>Back</button>}<button className="primary" onClick={()=>morningStep<4?setMorningStep(s=>s+1):finishMorning()}>{morningStep<4?"Continue":"Begin the day"}</button></div></div></Modal>}
 </main>
}

function Card({title,children,wide=false}:{title:string;children:React.ReactNode;wide?:boolean}){return <article className={`card ${wide?"wide":""}`}><h2>{title}</h2>{children}</article>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="modal" onClick={close}><div onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={close}>×</button>{children}</div></div>}
function Scale({label,value,onChange}:{label?:string;value:number;onChange:(n:number)=>void}){return <div className="scaleField">{label&&<label>{label} <b>{value}/10</b></label>}<div className="scale">{[1,2,3,4,5,6,7,8,9,10].map(n=><button key={n} className={value===n?"selected":""} onClick={()=>onChange(n)}>{n}</button>)}</div></div>}
function Choice({label,options,value,onChange}:{label?:string;options:string[];value:string;onChange:(s:string)=>void}){return <div className="choiceField">{label&&<label>{label}</label>}<div className="chips">{options.map(o=><button key={o} className={value===o?"selected":""} onClick={()=>onChange(o)}>{o}</button>)}</div></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article><label>{label}</label><strong>{value}</strong><span>{note}</span></article>}
